# Generated by Django 2.0.4 on 2018-08-10 23:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('career_levele', models.CharField(choices=[('ENTRY', 'Freshman'), ('EXPERIENCE_NM', 'Experienced (Non-Manager)'), ('MANAGER', 'Manager')], default='ENTRY', max_length=150)),
                ('job_type', models.CharField(choices=[('FULL', 'Full Time'), ('PART', 'Part Time'), ('REMOTE', 'Remotely')], default='FULL', max_length=150)),
                ('languages', models.CharField(choices=[('ARABIC', 'Arabic'), ('ENGLISH', 'English'), ('FRENCH', 'French')], default='FULL', max_length=150)),
                ('experience_needed', models.IntegerField(default=1)),
                ('open_vacancies', models.IntegerField(default=1)),
                ('applications', models.ManyToManyField(related_name='application_users', to='accounts.UserProfile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='accounts.Company')),
                ('saved_jobs', models.ManyToManyField(related_name='user_saved_jobs', to='accounts.UserProfile')),
            ],
        ),
    ]
