# Generated by Django 2.0.4 on 2018-08-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180806_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='afdf'),
            preserve_default=False,
        ),
    ]
