# Generated by Django 2.0.4 on 2018-08-04 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('career_levele', models.CharField(choices=[('ENTRY', 'Freshman'), ('EXPERIENCE_NM', 'Experienced (Non-Manager)'), ('MANAGER', 'Manager')], default='ENTRY', max_length=200)),
                ('job_type', models.CharField(choices=[('FULL', 'Full Time'), ('PART', 'Part Time'), ('REMOTE', 'Remotely')], default='FULL', max_length=200)),
                ('languages', models.CharField(choices=[('ARABIC', 'Arabic'), ('ENGLISH', 'English'), ('FRENCH', 'French')], default='FULL', max_length=200)),
                ('education', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=300)),
                ('salary', models.IntegerField()),
                ('experience', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, default='E:\\Learning\\Django-projects\\shaghalny\\Static\\images\\user.png', null=True, upload_to='users_images')),
            ],
        ),
    ]
